version: '3.8'

services:
    app:
        build:
            context: .
        container_name: pornstar_api
        volumes:
            - .:/var/www
        working_dir: /var/www
        ports:
            - "8000:8000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
            
    scheduler:
        build:
            context: .
        container_name: pornstar_scheduler
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - app
            - mysql
        command: bash -c "while true; do php artisan schedule:run --verbose >> /var/www/storage/logs/scheduler.log 2>&1; sleep 60; done"
        restart: unless-stopped
        
    queue:
        build:
            context: .
        container_name: pornstar_queue
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - app
            - mysql
        command: php artisan queue:work --queue=fetching,default --tries=3 --timeout=14400 --sleep=3 --max-time=86400
        restart: unless-stopped

volumes:
    dbdata:
