- name: Laravel Setup
  hosts: app
  become: false
  tasks:
    - name: Install Composer dependencies
      command: composer install
      args:
        chdir: /var/www

    - name: Generate app key
      command: php artisan key:generate
      args:
        chdir: /var/www

    - name: Set correct permissions
      file:
        path: "{{ item }}"
        state: directory
        mode: '0775'
      loop:
        - /var/www/storage

    - name: Run database migrations
      command: php artisan migrate --force
      args:
        chdir: /var/www
